"""add urls and fix relation group to playlists

Revision ID: 4e3a5e0acfb3
Revises: 8153cdc34074
Create Date: 2026-03-22 00:26:16.861451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3a5e0acfb3'
down_revision: Union[str, Sequence[str], None] = '8153cdc34074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('index_user_id', 'connections', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_group', 'connections', ['user_id', 'group_id'])
    op.add_column('tracks', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('tracks', sa.Column('audio_url', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'audio_url')
    op.drop_column('tracks', 'image_url')
    op.drop_constraint('uq_user_group', 'connections', type_='unique')
    op.drop_index('index_user_id', table_name='connections')
    # ### end Alembic commands ###
