"""add names & image url for groups and playlist

Revision ID: 8153cdc34074
Revises: 96f7feef2ca2
Create Date: 2026-03-16 14:22:31.704042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8153cdc34074'
down_revision: Union[str, Sequence[str], None] = '96f7feef2ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('image_url', sa.String(length=1000), nullable=True))
    op.add_column('playlists', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('playlists', sa.Column('image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'image_url')
    op.drop_column('playlists', 'name')
    op.drop_column('groups', 'image_url')
    # ### end Alembic commands ###
